package com.neogul.ui.view.agent;

import javax.annotation.PostConstruct;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
//@AutoGenerated
@SuppressWarnings("serial")
public class AgentFormDesign extends CssLayout {
    protected TextField agent_id;
	protected TextField nickname;
	protected TextField pc_mac;
	protected TextField pc_ip;
    protected TextField install_day;
    protected TextField connect_day;
    protected TextField user_id;
    protected ComboBox status;
    //protected ComboBox contract_idx_str;
    protected Button modify;
    protected Button block;
    protected Button unblock;
    protected Button add;
    protected Button save;
    protected Button cancel;
    protected Button delete;
    
    public AgentFormDesign() {
    	Design.read(this);
    	
    }
    
//    @PostConstruct
//    private void init() {
//		// TODO Auto-generated method stub
//    	productName=new TextField("Product name");
//    	price=new TextField("Price");
//    	stockCount=new TextField("In Stock");
//    	availability= new ComboBox("Availability");
//    	category=new OptionGroup("Categories");
//    	save=new Button("save");
//    	cancel=new Button("Cancel");
//    	delete=new Button("Delete");
//    	
//    	addComponents(productName,price,stockCount,availability,category,save,cancel,delete);
//    	
//	}
    
}