package com.neogul.ui.view.reclist;

import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
//@AutoGenerated
@SuppressWarnings("serial")
public class ReclistFormDesign extends CssLayout {
    
	protected TextField name;
    protected TextField price;
    protected Button add;
    protected Button save;
    protected Button cancel;
    protected Button delete;
    
   
    
    public ReclistFormDesign() {
    	Design.read(this);
    	
    }
    
//    @PostConstruct
//    private void init() {
//		// TODO Auto-generated method stub
//    	productName=new TextField("Product name");
//    	price=new TextField("Price");
//    	stockCount=new TextField("In Stock");
//    	availability= new ComboBox("Availability");
//    	category=new OptionGroup("Categories");
//    	save=new Button("save");
//    	cancel=new Button("Cancel");
//    	delete=new Button("Delete");
//    	
//    	addComponents(productName,price,stockCount,availability,category,save,cancel,delete);
//    	
//	}
    
}